discord-token = ""
discord-application = 0

[servers.test1]
address = "localhost:37015"
password = "myrconpassword"
channel = 1000000000000000000

[servers.test2]
address = "localhost:37016"
password = "myrconpassword"
channel = 1000000000000000000

[maps]
mp_angel_city = "Angel City"
mp_black_water_canal = "Black Water Canal"
mp_box = "Box"
mp_coliseum = "Coliseum"
mp_coliseum_column = "Pillars"
mp_colony02 = "Colony"
mp_complex3 = "Complex"
mp_crashsite3 = "Crash Site"
mp_drydock = "Drydock"
mp_eden = "Eden"
mp_forwardbase_kodai = "Forwardbase Kodai"
mp_glitch = "Glitch"
mp_grave = "Boomtown"
mp_homestead = "Homestead"
mp_lf_deck = "Deck"
mp_lf_meadow = "Meadow"
mp_lf_stacks = "Stacks"
mp_lf_township = "Township"
mp_lf_traffic = "Traffic"
mp_lf_uma = "UMA"
mp_lobby = "Lobby"
mp_relic02 = "Relic"
mp_rise = "Rise"
mp_thaw = "Exoplanet"
mp_wargames = "War Games"

[modes]
private_match = "Private Match"
aitdm = "Attrition"
at = "Bounty Hunt"
coliseum = "Coliseum"
cp = "Amped Hardpoint"
ctf = "Capture the Flag"
fd = "Frontier Defense"
fd_easy = "Frontier Defense (Easy)"
fd_hard = "Frontier Defense (Hard)"
fd_insane = "Frontier Defense (Insane)"
fd_master = "Frontier Defense (Master)"
fd_normal = "Frontier Defense (Regular)"
lf = "Live Fire"
lts = "Last Titan Standing"
mfd = "Marked for Death"
ps = "Pilots vs. Pilots"
solo = "Campaign"
tdm = "Skirmish"
ttdm = "Titan Brawl"
alts = "Aegis Last Titan Standing"
attdm = "Aegis Titan Brawl"
ffa = "Free For All"
fra = "Free Agents"
holopilot_lf = "The Great Bamboozle"
rocket_lf = "Rocket Arena"
turbo_lts = "Turbo Last Titan Standing"
turbo_ttdm = "Turbo Titan Brawl"
chamber = "One in the Chamber"
ctf_comp = "Competitive CTF"
fastball = "Fastball"
gg = "Gun Game"
hidden = "The Hidden"
hs = "Hide and Seek"
"inf" = "Infection"
kr = "Amped Killrace"
sbox = "Sandbox"
sns = "Sticks and Stones"
tffa = "Titan FFA"
tt = "Titan Tag"
sp_coop = "Campaign Coop"
